version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      - db

  db:
    image: postgres

    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

    ports:
      - "5433:5432"















#version: '3'
#
#services:
#
#
#  db:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_DB: db1
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 123
#    ports:
#      - "5433:5432"
